import 'package:flutter/material.dart';
import 'package:safehaven_dashboard/constants/app_colors.dart';
import 'package:safehaven_dashboard/models/incident.dart';
import 'dart:html' as html;

class ReportDownloader extends StatelessWidget {
  final Incident incident;
  const ReportDownloader({super.key, required this.incident});

  // void _downloadReport(BuildContext context) {
  //   // For Phase 1 — show snackbar confirmation
  //   // Phase 2 — generate actual PDF
  //   ScaffoldMessenger.of(context).showSnackBar(
  //     SnackBar(
  //       content: Text(
  //         '📄 Report for ${incident.type} @ ${incident.location} downloaded',
  //       ),
  //       backgroundColor: AppColors.accentGreen,
  //       duration: const Duration(seconds: 2),
  //     ),
  //   );
  // }

  void _downloadReport(BuildContext context) {
    final content =
        '''
SAFEHAVEN INCIDENT REPORT
==========================
Type:      ${incident.type} Emergency
Location:  ${incident.location}
Status:    ${incident.status.toUpperCase()}
Time:      ${incident.timestamp}
Staff:     ${incident.assignedStaff ?? 'Not assigned'}

AI ANALYSIS:
${incident.aiReport ?? 'Report not available'}

Generated by SafeHaven Command System
  ''';

    // Creates and downloads a .txt file in browser
    final blob = html.Blob([content], 'text/plain');
    final url = html.Url.createObjectUrlFromBlob(blob);
    html.AnchorElement(href: url)
      ..setAttribute('download', 'safehaven_report_${incident.id}.txt')
      ..click();
    html.Url.revokeObjectUrl(url);
  }

  @override
  Widget build(BuildContext context) {
    return OutlinedButton.icon(
      style: OutlinedButton.styleFrom(
        side: BorderSide(color: Colors.white24),
        padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
      ),
      onPressed: () => _downloadReport(context),
      icon: const Icon(Icons.download, color: Colors.white54, size: 16),
      label: const Text(
        'DOWNLOAD REPORT',
        style: TextStyle(color: Colors.white54, fontSize: 11, letterSpacing: 1),
      ),
    );
  }
}
